### ISSUE TITLE
How to setup for signInWithPhoneNumber?

### ISSUE THREAD

**Issue by CavalcanteLeo** [lupas/nuxt-fire-demo#17]
How to setup for signInWithPhoneNumber, since i need to pass RecaptchaVerifier?

Is there any demo available for `signInWithPhoneNumber` and `otp confirmation`

**Comment by lupas** [comment]
Follow this:

https://firebase.google.com/docs/auth/web/phone-auth

Replace ‘firebase.auth()’ with ‘$fireAuth’ and ‘firebase.auth’ with ‘$fireAuthObj’

--
Sent from Mobile
________________________________

**Comment by CavalcanteLeo** [comment]
wooow, thanks for a quick answer.

I will try it now

**Comment by CavalcanteLeo** [comment]
the code i have is mostly working:

```js
mounted() {
    this.initReCaptcha()
},
methods: {
    async verifyPhone() {
        try {
            await this.$fireAuth.signInWithPhoneNumber(
                'this.phoneNumber',
                this.appVerifier
            )
        } catch (e) {
            console.log('error', e)
        }
    },
    verifyOtp() {
        this.$fireAuthObj.confirmationResult
            .confirm(this.otp)
            .then(function(result) {
                console.log('result', result)
            })
            .catch(function(error) {
                console.log('error', error)
            })
    },
    initReCaptcha() {
        setTimeout(() => {
            const appVerifier = new this.$fireAuthObj.RecaptchaVerifier(
                'recaptcha-container',
                {
                    size: 'invisible',
                    callback(response) {
                        console.log('response', response)
                    },
                    'expired-callback'() {
                        console.log('expired-callback')
                    }
                }
            )
            this.appVerifier = appVerifier
        }, 1000)
    }
}
```

but i can't verify the OTP, neither `this.$fireAuthObj.confirmationResult.confirm(this.otp)` and `this.$fireAuth.confirmationResult.confirm(this.otp)` are working.

how can i invoke `confirmationResult.confirm` ??

**Comment by rajesh-h** [comment]
@CavalcanteLeo Thank you for the above code.
Was your application was SPA or universal? How did you manage user session like user need not login everytime.
Do you have full example of this ? 

Your help will be much appreciated.
