### ISSUE TITLE
Problems accessing firestore on page refresh

### ISSUE THREAD

**Issue by bozobit** [lupas/nuxt-fire-demo#30]
This issue is actually discussed here https://github.com/nuxt-community/firebase-module/issues/314, but I have been able to replicate the problem by making a few small adds to `nuxt-fire-demo`.  (https://github.com/bozobit/nuxt-fire-demo-fs-issue)  The problem is with refreshing a page that access Firestore documents that are protected by authentication rules (https://github.com/nuxt-community/firebase-module/issues/314#issuecomment-708148391).   I'm quite new to all this, so please let me know if I'm not raising this the right way.

**Comment by lupas** [comment]
Hey @bozobit 

As discussed in discord here again in short form for future reference:

- The `ssr: true` option does not log in the Client SDK on the server.
- The Client SDK is not meant to be used on server with multiple users potentially logged in simultenously
- Therefore, such calls would need to be made e.g. in mounted() hooks on the client side.
- Nevertheless we have **experimental** feature that does a `serverLogin` by creating a new session for each user on the server
- We however do not thing this approach should be used on any productive page and is just here to play around and to "maybe" find a well working solution one day

I also updated the documentation accordingly:

https://firebase.nuxtjs.org/service-options/auth#ssr

<img width="664" alt="Screenshot 2020-10-16 at 00 20 36" src="https://user-images.githubusercontent.com/4020037/96191979-7250f380-0f45-11eb-99a6-49936c127e9a.png">

Hope that makes the functionality clearer.

Thanks a lot for the issue, I appreciate any input if something is unclear so I can improve it :)

**Comment by bozobit** [comment]
Thanks so much!   I will take your advice regarding using the mounted hooks and see how that goes.
